### ISSUE TITLE
empty values showed as 'null'

### ISSUE THREAD

**Issue by PatrickVerhoeven** [synobsys/mendix-PivotTableWidget#1]
In Internet Explorer (version 10 and higher) empty values are showed as 'null' instead of empty. In Firefox and chrome the values are showed correctly. See screenshot.

Regards,
Patrick

![pivot_null_values](https://cloud.githubusercontent.com/assets/8803565/5775718/0e6c7d88-9d7e-11e4-9ca1-b3e775035443.png)

**Comment by mgroeneweg** [comment]
Thanks for the feedback, I will look into it soon.

Regards,

Marcel

**Comment by mgroeneweg** [comment]
When a cell has no value, I use &nbsp; to make sure that the cell is rendered. I have IE11, which displays the page correctly but does not render the &nbsp;

Could you share a little test project? I would like to know the widget settings and the data that was returned

**Comment by PatrickVerhoeven** [comment]
The problem is in a customer database so I do not have a test project right away

Actually the problem only exists when data does not exist in the database. According to my screenshot I will describe the situation in more detail. I have 2 years, 2013 and 2014.

For the first line (values resp. 62 and 37) 2 records are available in the database. No problem here.
For the fourth line I do have a record for 2014 but not for 2013. The 'null' is correct, but not as presentation value.

In Firefox and Chrome the 'null'-value is showed as ' ' but in IE as 'null'

**Comment by mgroeneweg** [comment]
Is it possible for the customer to test this using IE11? I want to know where the issue is. I noticed that comments are rendered as is, so in my previous comment the & nbsp; was lost. (Without the space after the & of course.)

**Comment by PatrickVerhoeven** [comment]
We have tested this in IE11 and we have the same problem.

**Comment by mgroeneweg** [comment]
I'm at a loss here. I really need a test project to reproduce this as my tests run just fine on IE11

**Comment by PatrickVerhoeven** [comment]
Ok, I am going to arrange that Marcel.

**Comment by PatrickVerhoeven** [comment]
I have created a small test project in Mx5.9.1. Can I send the .mpk to you by email?

**Comment by mgroeneweg** [comment]
Use the same as my github id and I work for synobsys in nl... :-)

**Comment by PatrickVerhoeven** [comment]
:-)

**Comment by mgroeneweg** [comment]
Fixed!

**Comment by PatrickVerhoeven** [comment]
Thanks Marcel for the quick response!
